"""
backend/database.py — Project DRISHTI
=====================================
Persistent SQLite Database & SQLAlchemy ORM for Alert Tracking.

Defines the SQLite connection engine, session factory, and Alert model.
"""

import os
from datetime import datetime
from typing import Optional, Dict, Any
from dotenv import load_dotenv
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, JSON
from sqlalchemy.orm import declarative_base, sessionmaker, Session

# Load environment variables
load_dotenv()

# Ensure local data directory exists for SQLite storage
DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
os.makedirs(DATA_DIR, exist_ok=True)

DEFAULT_SQLITE_PATH = os.path.join(DATA_DIR, "drishti.db")
DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{DEFAULT_SQLITE_PATH}")

# SQLite requires check_same_thread=False for multi-threaded access in FastAPI
connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

engine = create_engine(
    DATABASE_URL,
    connect_args=connect_args,
    echo=False,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()


# ─────────────────────────────────────────────
# ALERT MODEL
# ─────────────────────────────────────────────
class Alert(Base):
    """
    Alert record representing a cybercrime prediction dispatched for field action.

    Status lifecycle:
      - PENDING:     Generated by ML pipeline, awaiting officer dispatch
      - DISPATCHED:  Dispatched to nearest police unit / ATM interceptor
      - INTERCEPTED: Suspect physically intercepted or funds successfully frozen
      - FAILED:      Suspect escaped or withdrawal occurred before interception
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    complaint_id = Column(String(64), index=True, nullable=False)
    predicted_location = Column(JSON, nullable=True)  # Stores lat, lon, radius, ATM candidates
    confidence = Column(Float, nullable=True)         # Model confidence 0.0 - 1.0
    status = Column(String(32), default="PENDING", nullable=False)  # PENDING, DISPATCHED, INTERCEPTED, FAILED
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "alert_id": self.id,
            "complaint_id": self.complaint_id,
            "predicted_location": self.predicted_location,
            "confidence": round(self.confidence, 4) if self.confidence is not None else None,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


# ─────────────────────────────────────────────
# DATABASE HELPERS & DEPENDENCIES
# ─────────────────────────────────────────────
def init_db():
    """Create all database tables if they do not exist."""
    Base.metadata.create_all(bind=engine)


def get_db():
    """FastAPI dependency for yielding DB sessions."""
    db: Session = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# Ensure tables are created on module load
init_db()
