"""
backend/database.py — Project DRISHTI
=====================================
Persistent SQLite Database & SQLAlchemy ORM for Alert Tracking and Authentication.

Defines the SQLite connection engine, session factory, Alert model, and
the User model for authentication.  The init_db() / init_users() helpers
are called once at startup — they are safe to call multiple times.
"""

import os
from datetime import datetime, timezone
from typing import Optional, Dict, Any
from dotenv import load_dotenv
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, JSON
from sqlalchemy.orm import declarative_base, sessionmaker, Session

# Load environment variables
load_dotenv()

# Ensure local data directory exists for SQLite storage
DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
os.makedirs(DATA_DIR, exist_ok=True)

DEFAULT_SQLITE_PATH = os.path.join(DATA_DIR, "drishti.db")
DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{DEFAULT_SQLITE_PATH}")

# SQLite requires check_same_thread=False for multi-threaded access in FastAPI
connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

engine = create_engine(
    DATABASE_URL,
    connect_args=connect_args,
    echo=False,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()


# ─────────────────────────────────────────────
# ALERT MODEL
# ─────────────────────────────────────────────
class Alert(Base):
    """
    Alert record representing a cybercrime prediction dispatched for field action.

    Status lifecycle:
      - PENDING:     Generated by ML pipeline, awaiting officer dispatch
      - DISPATCHED:  Dispatched to nearest police unit / ATM interceptor
      - INTERCEPTED: Suspect physically intercepted or funds successfully frozen
      - FAILED:      Suspect escaped or withdrawal occurred before interception
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    complaint_id = Column(String(64), index=True, nullable=False)
    predicted_location = Column(JSON, nullable=True)  # Stores lat, lon, radius, ATM candidates
    confidence = Column(Float, nullable=True)         # Model confidence 0.0 - 1.0
    status = Column(String(32), default="PENDING", nullable=False)  # PENDING, DISPATCHED, INTERCEPTED, FAILED
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "alert_id": self.id,
            "complaint_id": self.complaint_id,
            "predicted_location": self.predicted_location,
            "confidence": round(self.confidence, 4) if self.confidence is not None else None,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


# ─────────────────────────────────────────────
# DATABASE HELPERS & DEPENDENCIES
# ─────────────────────────────────────────────
def init_db():
    """
    Create all database tables if they do not exist.
    Safe to call multiple times — uses CREATE TABLE IF NOT EXISTS semantics.
    """
    # Import User model here to ensure it is registered on Base.metadata
    # before create_all() is called.
    from backend.auth.user_model import User  # noqa: F401
    Base.metadata.create_all(bind=engine)


def init_users():
    """
    Create the demo user account on first-time startup.

    - Only runs if the users table is completely empty.
    - Reads credentials from environment variables:
        DRISHTI_DEMO_USERNAME  (default: admin)
        DRISHTI_DEMO_PASSWORD  (default: Drishti@2026)
    - Password is bcrypt-hashed before storage — NEVER stored plaintext.
    - Safe to call on every startup; does nothing if users already exist.
    """
    from backend.auth.user_model import User
    from backend.auth.security import hash_password

    demo_username = os.getenv("DRISHTI_DEMO_USERNAME", "admin").strip().lower()
    demo_password = os.getenv("DRISHTI_DEMO_PASSWORD", "Drishti@2026")
    demo_role     = os.getenv("DRISHTI_DEMO_ROLE", "admin")
    demo_email    = os.getenv("DRISHTI_DEMO_EMAIL", "admin@drishti.local")

    db: Session = SessionLocal()
    try:
        existing = db.query(User).filter(User.username == demo_username).first()
        if existing is not None:
            return  # Demo user already exists — do nothing

        print(f"[DRISHTI-AUTH] Demo user '{demo_username}' not found. Creating account (role: {demo_role})")
        demo_user = User(
            username=demo_username,
            email=demo_email,
            password_hash=hash_password(demo_password),
            role=demo_role,
            is_active=True,
        )
        db.add(demo_user)
        db.commit()
        print(f"[DRISHTI-AUTH] Demo account created. Username: '{demo_username}'.")
        print(f"[DRISHTI-AUTH] Set DRISHTI_DEMO_PASSWORD in .env to change the default password.")
    except Exception as exc:
        db.rollback()
        print(f"[DRISHTI-AUTH] Warning: could not create demo user: {exc}")
    finally:
        db.close()


def get_db():
    """FastAPI dependency for yielding DB sessions."""
    db: Session = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# Ensure tables are created on module load
init_db()
